YOLO_MODEL = "yolov8n.pt"
DETECTION_CONFIDENCE = 0.45
PERSON_CLASS_ID = 0

POSE_CONFIDENCE = 0.5
MAX_IDENTITIES = 10
IDENTITY_IOU_THRESHOLD = 0.35
UNKNOWN_LABEL_PREFIX = "Person"
IDENTITY_TIMEOUT_SECONDS = 8

SHOULDER_TILT_THRESHOLD = 15
FORWARD_HEAD_RATIO = 0.15
SPINE_ANGLE_THRESHOLD = 160

FRAME_WIDTH = 1280
FRAME_HEIGHT = 720
MAX_FPS = 60

# Face recognition
FACE_DB_PATH = "face_db.pkl"          # persists between runs
FACE_MATCH_TOLERANCE = 0.5            # lower = stricter

# Object detection — all COCO classes except person
SHOW_OBJECTS = True
OBJECT_CONFIDENCE = 0.4
OBJECT_LABELS_SKIP = []               # add class names to hide