YOLO_MODEL = "yolov8n.pt"
DETECTION_CONFIDENCE = 0.5
PERSON_CLASS_ID = 0

POSE_CONFIDENCE = 0.5
MAX_IDENTITIES = 10
IDENTITY_IOU_THRESHOLD = 0.4
UNKNOWN_LABEL_PREFIX = "Person"
IDENTITY_TIMEOUT_SECONDS = 5

SHOULDER_TILT_THRESHOLD = 15
FORWARD_HEAD_RATIO = 0.15
SPINE_ANGLE_THRESHOLD = 160

FRAME_WIDTH = 1280
FRAME_HEIGHT = 720
MAX_FPS = 30
